services:
  cdocweb:
    build:
      context: ..
      dockerfile: infra/cdoc_web.Dockerfile
    ports: 
      - "${CDOC_PORT}:80"
    networks:
      - santa-network


networks:
  santa-network:
    external: true
    name: santanet
